#!/bin/bash

LOG=$(docker exec -it squid cat /var/log/squid3/access.log)
CONF=$(docker exec -it squid cat /etc/squid3/squid.conf)
FILE="tmp/res.log"
#Temp while waiting for the big wrap
touch $FILE

TYPE=`echo "$CONF" | grep cache_replacement_policy | cut -c26- | sed 's/.$//'`
#Cache size
SIZE=`echo "$CONF" | grep cache_mem | tr -dc '0-9'`
#Cache hit
HIT=`echo "$LOG" | grep TCP.*_HIT | wc -l`
#Cache miss
MISS=`echo "$LOG" | grep TCP.*_MISS | wc -l`
#All intercepted request
TOTAL=`echo "$LOG" | wc -l`
RES="$TYPE $SIZE $HIT $MISS $TOTAL"
echo "$RES" >> $FILE
