[
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"biographies"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"nonparliamentary loaches"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"dognapping noodles"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"mementos"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"bruskness"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"distillable uxoriousness trembliest"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"hedgehogs barstools"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"incriminated"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"nourishes"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"pronouncing reworking hillocks"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"abysm"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"histrionics unfreezes"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"advisatory blacktops"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"imperiousness bucketing"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"biculturalism panders freethinker"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"misguide impoundments menologies"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"sugarplums"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"stutterer"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
{ '?label': '"inpatient wonderfully"',
  '?comment': '"spiry floccular advertent unkindest poetizers overdesirous fluttered tsuba unstablest nonphysically haberdasheries greenstick vocatives hamstring formating ebullience mechanistic dragropes baulking boulimia vitamines lukewarmly canceled longwise banked crisic potterers draughts newsiest stymies tenfolds mortuaries unsociable disengaging condoling vitalizer pathogenically forefoot forboding unimpressible picnickers journalistically firstlings transmitters cragsman missaid lightens picketing classing hinnies stylers admixtures"',
  '?producer': '"cashmeres prearranges"',
  '?productFeature': '"demagnetize guessing"',
  '?propertyTextual1': '"alcoholization radiologies substage pedophile squeezers reserved monetizes threaped coonskin bittered"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual2': '"gales fermata finks douser commutative kippered incumbents undulatory banco foreside"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyTextual3': '"keratin papooses fastings incepting unrobes bewitching masqueraded sinks myriapods hundredweight colonized chopstick malefic calculably"^^http://www.w3.org/2001/XMLSchema#string',
  '?propertyNumeric1': '"476"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyNumeric2': '"70"^^http://www.w3.org/2001/XMLSchema#integer',
  '?propertyTextual4': null,
  '?propertyTextual5': null,
  '?propertyNumeric4': null }
]
[
]
[
]
[
]
[
]
