#!/bin/bash
if [ "$1" = "-c" ]; then
   #Only cache hit
   docker exec -it squid grep _HIT /var/log/squid3/access.log | sed 's/^.*GET //' | sed 's/ - HIER_.*$//' | sort | uniq -cd | sort -r
else
   #Every requests
   docker exec -it squid sed 's/^.*GET //' /var/log/squid3/access.log | sed 's/ - HIER_.*$//' | sort | uniq -cd | sort -r
fi
