#!/bin/bash
if [ ! $# -eq 2 ]
then
   echo "Needs exactly 2 argument. Usage: exStart NumberOfQueries ClientCacheSize"
   exit 1
fi

NBQUERIES=$1
CLIENTCACHE=$2

#Start the server
./dockServer
touch tmp/extracted.tmp
#Get the server ip
SERVIP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ldf-server)
RES=0
ALL=0
(( NBQUERIES=NBQUERIES-1 ))
for run in `seq 0 2`;
do
   #Need to find a better way to split query
   RES=0
   for nbq in `seq 0 $NBQUERIES`;
   do
      LOG=""
      TOT=0
      LOGNB=0
      ./extractURLQuerie ../zip/queries/scale1000_queries.json $nbq $SERVIP > tmp/extracted.tmp
      #Start client
      (( suiv=nbq+1 ))
      LOG=$(docker run --name ldf-allclient -v $(pwd)/../zip/queries/scale1000_queries.json:/tmp/queries.json ldf-allclient http://$SERVIP:3000/scale1000 /tmp/queries.json -s $nbq -e $suiv -c $CACHE -l info 2>&1)
      #Remove client
      docker rm -f ldf-allclient
      #Only keep URL
      LOG=`echo "$LOG" | awk '{print $11}'`
      TOT=`echo "$LOG" | wc -l`
      #Regrouping url appearing multiple times
      LOG=`echo "$LOG" | sort | uniq -c`
      #URL coming from the querie
      LOG=`echo "$LOG" | fgrep -f tmp/extracted.tmp`
      LOGNB=`echo "$LOG" | sed 's/^ *//' | awk '{s+=$1} END {print s}'`
      LOGNB=$(echo "scale=4; ($LOGNB*100/$TOT)" | bc)
      RES=$(echo "scale=4; ($RES*$nbq+$LOGNB)/($nbq+1)" | bc)
   done
   ALL=$(echo "scale=4; ($ALL*$run+$RES)/($run+1)" | bc)
done
echo "$ALL"
rm tmp/extracted.tmp
#Stopping the server
docker rm -f ldf-server
