#!/bin/bash
#TODO Look into args:- name for output graph
#                    - number of runs per config
#                    - directory with squid conf (Special case for one conf?)
#                    - Server address instead of starting mine
#     Set echoes to know where he's at (also kindly ask for sudo permission for iptables)
#     Probably something else, look into it

#Output file
FILE="tmp/res.log"
rm $FILE
touch $FILE

#Start the server
./dockServer

#Setting the iptables
#sudo ./setIptables

POLICY=""
SIZE=""
HITAVG=0
TOT=""
#Loop between all squid conf files
for squidC in `ls conf` ;
do
   #Select the good conf
   rm squid.conf
   cp conf/$squidC squid.conf
   
   #Start squid
   ./dockSquid
   
   #Get policy and size initialised for this run
   #Read conf file
   CONF=$(docker exec squid cat /etc/squid3/squid.conf)
   #Find why I had  | sed 's/.$//' and now I don't want it
   POLICY=`echo "$CONF" | grep cache_replacement_policy | cut -c26-`
   POLICY=${POLICY// /-}
   SIZE=`echo "$CONF" | grep cache_mem | tr -dc '0-9'`
   echo "$POLICY : $SIZE"
   #Loop the runs
   for run in `seq 0 2`;
   do
      #Run the client
      ./dockClient
      
      #Read cache log
      LOG=$(docker exec squid cat /var/log/squid3/access.log)
      #Save too much, remove after test
      #echo "$LOG" > "tmp/curLog/$POLICY-$SIZE-$run.log"
      #Compute the new hit average
      HITCUR=`echo "$LOG" | grep TCP.*_HIT | wc -l`
      TOT=`echo "$LOG" | wc -l`
      echo "Hitcur for run $run : $HITCUR, total is $TOT"
      HITCUR=$(echo "scale=2; ($HITCUR/$TOT)*100" | bc)
      echo "Percentage calculated : $HITCUR"
      HITAVG=$(echo "scale=2; ($HITAVG*$run+$HITCUR)/($run+1)" | bc)
      
      #Reset Squid to erase the cache
      ./hardSquidReset
   done
   #Reset Squid to erase the cache
   docker rm -f squid
   #Write the average hit rate for that conf
   echo "$POLICY $SIZE $HITAVG" >> $FILE
done

#Making the graph
julia barHit.jl $FILE

#Stopping the server
docker stop ldf-server

#Clean up
./remIptables
rm squid.conf
#rm $FILE
